- name: Update README with activity
  uses: athul/update-readme@v2
  with:
    gh_token: ${{ secrets.GITHUB_TOKEN }}
    username: sebastian8068
    readme: README.md
    max_lines: 10
    commit_message: "Update recent activity"
    commit_name: GitHub Activity Readme
    commit_email: github-actions[bot]@users.noreply.github.com
