name: Update README
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
jobs:
  build:
    name: Update this repo's README with recent activity
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Update README with activity
        uses: TheDanniCraft/activity-log@v1
        with:
          GITHUB_USERNAME: sebastian8068
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAX_LINES: 10
          COMMIT_MSG: "Update recent activity"
          FILTER_EVENTS: "PushEvent,CreateEvent,IssueCommentEvent,IssuesEvent,PullRequestEvent,ReleaseEvent,WatchEvent,ForkEvent"
          COMMIT_NAME: "GitHub Activity Readme"
          COMMIT_EMAIL: "github-actions[bot]@users.noreply.github.com"
